server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      show-sql: true

indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: PlayBack.Ru
      domain: playback.ru
    - url: https://ipfran.ru/
      name: ipfran
      domain: ipfran.ru
    - url: https://dimonvideo.ru/
      name: dimonvideo
      domain: dimonvideo.ru
    - url: https://www.svetlovka.ru/
      name: svetlovka
      domain: svetlovka.ru